//
// Created by lukasz on 17.01.26.
//

#ifndef DINING_PHILOSOPHERS_SRC_DINING_PHILOSOPHERS_ENTITIES_INCLUDE_DINING_PHILOSOPHERS_ENTITIES_FORK_HPP_
#define DINING_PHILOSOPHERS_SRC_DINING_PHILOSOPHERS_ENTITIES_INCLUDE_DINING_PHILOSOPHERS_ENTITIES_FORK_HPP_

namespace dining_philosophers_entities {

class Fork {

};

}

#endif //DINING_PHILOSOPHERS_SRC_DINING_PHILOSOPHERS_ENTITIES_INCLUDE_DINING_PHILOSOPHERS_ENTITIES_FORK_HPP_
